/**
 * Seed script — run with: node supabase/seed.mjs
 * Reads NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY from .env.local
 */
import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))

// Parse .env.local manually (no dotenv needed)
const envPath = resolve(__dir, '../.env.local')
const env = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .filter((l) => l && !l.startsWith('#') && l.includes('='))
    .map((l) => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()] })
)

const url = env['NEXT_PUBLIC_SUPABASE_URL']
const key = env['SUPABASE_SERVICE_ROLE_KEY'] || env['NEXT_PUBLIC_SUPABASE_ANON_KEY']

if (!url || !key) {
  console.error('❌  Missing NEXT_PUBLIC_SUPABASE_URL or key in .env.local')
  process.exit(1)
}

const supabase = createClient(url, key)

const POLICIES = [
  {id:1,title:"Nigeria Data Protection Act 2023",country:"Nigeria",flag:"🇳🇬",region:"West Africa",group:"ECOWAS",year:2023,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Act No. 3 of 2023",enacted:"June 12, 2023",inForce:"June 12, 2023",authority:"National Assembly / NDPC",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.85,0.78,0.82,0.71,0.88],summary:"Replaces the 2019 NDPR. Establishes NDPC as independent regulator. Introduces controller/processor liability, data subject rights, cross-border transfer controls and 72-hr breach notification.",tags:["Data Protection","Privacy","GDPR-Aligned","West Africa"],whoAffects:"Data controllers, processors, public & private entities operating in Nigeria.",sectorImpact:"All sectors handling personal data",demand:"To protect personal data and establish NDPC as independent regulator.",keyObs:"Lawful basis, data minimisation, 72-hr breach notification, DPO appointment",areas:["Data Protection","Legislation"],updated:"Jun 12, 2023"},
  {id:2,title:"Kenya Data Protection Act 2019",country:"Kenya",flag:"🇰🇪",region:"East Africa",group:"EAC",year:2019,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"No. 24 of 2019",enacted:"Nov 8, 2019",inForce:"Nov 25, 2019",authority:"National Assembly / ODPC",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.83,0.80,0.79,0.74,0.85],summary:"Kenya's first standalone data protection law. Establishes ODPC. Grants data subjects rights to access, correction, deletion and portability.",tags:["Data Protection","Privacy","East Africa","GDPR-Inspired"],whoAffects:"All data controllers and processors in Kenya.",sectorImpact:"All sectors including government",demand:"Protect personal data of Kenyan residents.",keyObs:"Consent, data subject rights, impact assessments, breach notification",areas:["Data Protection","Legislation"],updated:"Nov 8, 2019"},
  {id:3,title:"South Africa POPIA 2013",country:"South Africa",flag:"🇿🇦",region:"Southern Africa",group:"SADC",year:2013,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Act 4 of 2013",enacted:"Nov 26, 2013",inForce:"Jul 1, 2021",authority:"Parliament / Information Regulator",closestFW:"GDPR (EU)",simLevel:"Very High",oecd:[0.88,0.84,0.86,0.80,0.91],summary:"Protection of Personal Information Act. Africa's most comprehensive data protection law pre-GDPR. Eight conditions for lawful processing.",tags:["Data Protection","GDPR-Aligned","Southern Africa","Comprehensive"],whoAffects:"All responsible parties processing personal information in South Africa.",sectorImpact:"All sectors",demand:"Regulate processing of personal information.",keyObs:"Eight conditions, PAIA integration, transborder flows, direct marketing",areas:["Data Protection"],updated:"Jul 1, 2021"},
  {id:4,title:"Ghana Data Protection Act 2012",country:"Ghana",flag:"🇬🇭",region:"West Africa",group:"ECOWAS",year:2012,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Act 843",enacted:"May 16, 2012",inForce:"Oct 16, 2012",authority:"Parliament / Data Protection Commission",closestFW:"EU Directive 95/46/EC",simLevel:"High",oecd:[0.75,0.70,0.72,0.65,0.78],summary:"Ghana's first dedicated data protection legislation. Establishes Data Protection Commission. Requires registration of data controllers.",tags:["Data Protection","West Africa","Privacy"],whoAffects:"Data controllers operating in Ghana.",sectorImpact:"Telecoms, banking, health",demand:"Regulate personal data processing and protect privacy.",keyObs:"Registration regime, data subject rights, cross-border transfers",areas:["Data Protection"],updated:"Oct 16, 2012"},
  {id:5,title:"Rwanda Data Protection Law 2021",country:"Rwanda",flag:"🇷🇼",region:"East Africa",group:"EAC",year:2021,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law No. 058/2021",enacted:"Oct 15, 2021",inForce:"Oct 15, 2021",authority:"Parliament / RISA",closestFW:"GDPR (EU)",simLevel:"Very High",oecd:[0.90,0.87,0.88,0.82,0.92],summary:"Rwanda's first comprehensive data protection law. Among the most GDPR-aligned in Africa. Introduces DPOs, impact assessments, 72-hr breach notification.",tags:["Data Protection","GDPR-Aligned","East Africa","Best-in-Class"],whoAffects:"All data controllers and processors in Rwanda.",sectorImpact:"All sectors",demand:"Regulate personal data processing.",keyObs:"DPO requirement, DPIA, breach notification, consent",areas:["Data Protection"],updated:"Oct 15, 2021"},
  {id:6,title:"Nigeria Cybercrime Act 2015",country:"Nigeria",flag:"🇳🇬",region:"West Africa",group:"ECOWAS",year:2015,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"Cybercrime Act 2015",enacted:"May 15, 2015",inForce:"May 15, 2015",authority:"National Assembly",closestFW:"Budapest Convention",simLevel:"Medium",oecd:[0.55,0.48,0.60,0.72,0.65],summary:"Nigeria's primary cybersecurity law. Criminalises hacking, cyberstalking, identity theft, cyberbullying.",tags:["Cybersecurity","West Africa","Criminal Law"],whoAffects:"All internet users and digital service providers.",sectorImpact:"ICT, finance, government",demand:"Prohibit and prevent cybercrime.",keyObs:"Critical infrastructure protection, electronic evidence, financial cybercrime",areas:["Cybersecurity"],updated:"May 15, 2015"},
  {id:7,title:"Kenya Computer Misuse and Cybercrimes Act 2018",country:"Kenya",flag:"🇰🇪",region:"East Africa",group:"EAC",year:2018,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"No. 5 of 2018",enacted:"May 16, 2018",inForce:"May 30, 2018",authority:"National Assembly",closestFW:"Budapest Convention",simLevel:"High",oecd:[0.60,0.55,0.65,0.75,0.70],summary:"Comprehensive cybercrime legislation. Criminalises computer misuse, data interference, cyber espionage. Establishes KE-CIRT/CC.",tags:["Cybersecurity","East Africa","CIRT"],whoAffects:"All internet users and service providers in Kenya.",sectorImpact:"ICT, government, finance",demand:"Prevent and prosecute cybercrime.",keyObs:"KE-CIRT/CC establishment, critical infrastructure, evidence standards",areas:["Cybersecurity"],updated:"May 30, 2018"},
  {id:8,title:"Ghana Cybersecurity Act 2020",country:"Ghana",flag:"🇬🇭",region:"West Africa",group:"ECOWAS",year:2020,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"Act 1038",enacted:"Dec 29, 2020",inForce:"Dec 29, 2020",authority:"Parliament / Cyber Security Authority",closestFW:"Budapest Convention",simLevel:"High",oecd:[0.62,0.58,0.68,0.78,0.72],summary:"Establishes Ghana Cyber Security Authority. Comprehensive framework for cybersecurity including critical information infrastructure protection.",tags:["Cybersecurity","West Africa","CSA"],whoAffects:"All digital service providers and critical infrastructure operators.",sectorImpact:"ICT, energy, finance, health",demand:"Regulate cybersecurity and protect critical infrastructure.",keyObs:"CSA establishment, CIIP, incident reporting, capacity building",areas:["Cybersecurity"],updated:"Dec 29, 2020"},
  {id:9,title:"South Africa Cybercrimes Act 2020",country:"South Africa",flag:"🇿🇦",region:"Southern Africa",group:"SADC",year:2020,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"Act 19 of 2020",enacted:"Jun 1, 2021",inForce:"Jun 1, 2021",authority:"Parliament",closestFW:"Budapest Convention",simLevel:"High",oecd:[0.65,0.60,0.70,0.80,0.75],summary:"Criminalises cybercrimes including data breaches, ransomware, cyberbullying. Obligates reporting to SAPS.",tags:["Cybersecurity","Southern Africa","Criminal Law"],whoAffects:"Electronic communications service providers and all organisations.",sectorImpact:"All sectors",demand:"Criminalise cybercrimes and create reporting obligations.",keyObs:"72-hr reporting, malicious communications, extraterritorial jurisdiction",areas:["Cybersecurity"],updated:"Jun 1, 2021"},
  {id:10,title:"Mauritius Data Protection Act 2017",country:"Mauritius",flag:"🇲🇺",region:"Southern Africa",group:"SADC",year:2017,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Act No. 20 of 2017",enacted:"Jan 15, 2018",inForce:"Jan 15, 2018",authority:"National Assembly / Data Protection Commissioner",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.82,0.79,0.81,0.74,0.86],summary:"Updated data protection framework. GDPR-compliant. Introduces DPO requirement, data breach notification within 72 hours.",tags:["Data Protection","Southern Africa","GDPR-Aligned","Mauritius"],whoAffects:"All data controllers in Mauritius.",sectorImpact:"Finance, tourism, ICT",demand:"Modernise data protection regulation.",keyObs:"DPO, breach notification, PbD, data subject rights",areas:["Data Protection"],updated:"Jan 15, 2018"},
  {id:11,title:"Mauritius National AI Strategy 2018",country:"Mauritius",flag:"🇲🇺",region:"Southern Africa",group:"SADC",year:2018,status:"in-force",area:"Artificial Intelligence",instrument:"Strategy",act:"National AI Strategy 2018",enacted:"2018",inForce:"2018",authority:"Ministry of Technology / ICT Authority",closestFW:"OECD AI Principles",simLevel:"Medium",oecd:[0.72,0.68,0.65,0.70,0.67],summary:"Africa's first national AI strategy. Focuses on AI for economic transformation, smart cities, and inclusive growth.",tags:["AI","Strategy","Africa-First","Mauritius"],whoAffects:"Technology sector, government agencies, researchers.",sectorImpact:"ICT, finance, agriculture, health",demand:"Position Mauritius as Africa's AI hub.",keyObs:"AI lab, talent development, regulatory sandbox, AI ethics committee",areas:["Artificial Intelligence"],updated:"2018"},
  {id:12,title:"Rwanda National AI Policy 2023",country:"Rwanda",flag:"🇷🇼",region:"East Africa",group:"EAC",year:2023,status:"in-force",area:"Artificial Intelligence",instrument:"Policy",act:"National AI Policy 2023",enacted:"2023",inForce:"2023",authority:"MINICT / RDB",closestFW:"OECD AI Principles",simLevel:"High",oecd:[0.88,0.85,0.87,0.82,0.90],summary:"Comprehensive AI policy for Rwanda. Focus on responsible AI, data sovereignty, AI-driven public services.",tags:["AI","Policy","East Africa","Best Practice"],whoAffects:"AI developers, public institutions, private sector.",sectorImpact:"All sectors",demand:"Govern AI development and deployment responsibly.",keyObs:"Responsible AI, data governance, AI for SDGs, ethics framework",areas:["Artificial Intelligence"],updated:"2023"},
  {id:13,title:"Kenya National AI Strategy 2025",country:"Kenya",flag:"🇰🇪",region:"East Africa",group:"EAC",year:2025,status:"under-review",area:"Artificial Intelligence",instrument:"Strategy",act:"Draft National AI Strategy 2025",enacted:"—",inForce:"—",authority:"ICT Ministry",closestFW:"OECD AI Principles",simLevel:"High",oecd:[0.80,0.77,0.82,0.75,0.83],summary:"Kenya's draft AI strategy. Focus on AI skills, data infrastructure, responsible AI governance.",tags:["AI","Draft","East Africa","Kenya"],whoAffects:"All AI actors in Kenya.",sectorImpact:"Agriculture, health, finance, education",demand:"Develop AI governance framework for Kenya.",keyObs:"Responsible AI, talent pipeline, data infrastructure, AI safety",areas:["Artificial Intelligence"],updated:"2025"},
  {id:14,title:"Nigeria National Digital Economy Policy 2020",country:"Nigeria",flag:"🇳🇬",region:"West Africa",group:"ECOWAS",year:2020,status:"in-force",area:"Digital Economy",instrument:"Policy",act:"NDEPS 2020-2030",enacted:"2020",inForce:"2020",authority:"Federal Ministry of Communications",closestFW:"ITU Digital Economy Framework",simLevel:"Medium",oecd:[0.50,0.55,0.48,0.60,0.52],summary:"Nigeria's 10-year digital economy policy covering digital infrastructure, services, governance, skills.",tags:["Digital Economy","Strategy","West Africa","Nigeria"],whoAffects:"All digital economy actors in Nigeria.",sectorImpact:"All sectors",demand:"Transform Nigeria into a digital economy.",keyObs:"8 pillars, broadband target, digital skills, e-government",areas:["Digital Economy"],updated:"2020"},
  {id:15,title:"Kenya Digital Economy Blueprint 2019",country:"Kenya",flag:"🇰🇪",region:"East Africa",group:"EAC",year:2019,status:"in-force",area:"Digital Economy",instrument:"Strategy",act:"Digital Economy Blueprint 2019",enacted:"2019",inForce:"2019",authority:"ICT Ministry",closestFW:"ITU Digital Economy Framework",simLevel:"Medium",oecd:[0.48,0.52,0.50,0.58,0.54],summary:"Blueprint for Kenya's digital economy transformation. Five pillars including digital infrastructure and finance.",tags:["Digital Economy","Kenya","East Africa"],whoAffects:"Government, private sector, citizens.",sectorImpact:"All sectors",demand:"Build Kenya's digital economy.",keyObs:"Silicon Savannah, iHub ecosystem, Konza Technopolis, Ajira platform",areas:["Digital Economy"],updated:"2019"},
  {id:16,title:"Nigeria Electronic Fraud Prohibition Act 2018",country:"Nigeria",flag:"🇳🇬",region:"West Africa",group:"ECOWAS",year:2018,status:"in-force",area:"Digital Finance",instrument:"Legislation",act:"Advance Fee Fraud Amendment 2018",enacted:"2018",inForce:"2018",authority:"National Assembly / CBN",closestFW:"FATF Recommendations",simLevel:"Medium",oecd:[0.40,0.45,0.55,0.62,0.58],summary:"Strengthens legal framework against electronic fraud and financial cybercrime.",tags:["Digital Finance","Fraud","West Africa","CBN"],whoAffects:"Financial institutions, fintechs, payment processors.",sectorImpact:"Finance, fintech",demand:"Combat electronic fraud in financial sector.",keyObs:"AML/CFT integration, CBN supervision, sanctions",areas:["Digital Finance","Cybersecurity"],updated:"2018"},
  {id:17,title:"Nigeria eNaira CBN Guidelines 2021",country:"Nigeria",flag:"🇳🇬",region:"West Africa",group:"ECOWAS",year:2021,status:"in-force",area:"Digital Finance",instrument:"Regulation",act:"eNaira Guidelines 2021",enacted:"Oct 25, 2021",inForce:"Oct 25, 2021",authority:"Central Bank of Nigeria",closestFW:"BIS CBDC Framework",simLevel:"Medium",oecd:[0.42,0.48,0.55,0.65,0.60],summary:"Africa's first CBDC. CBN launched eNaira as digital version of naira with tier-based wallet system.",tags:["Digital Finance","CBDC","Africa-First","Nigeria","West Africa"],whoAffects:"Banks, fintechs, payment platforms, citizens.",sectorImpact:"Finance, retail",demand:"Launch first African CBDC for financial inclusion.",keyObs:"Tier 1/2/3 wallets, NIBSS integration, offline transactions, KYC",areas:["Digital Finance"],updated:"Oct 25, 2021"},
  {id:18,title:"Rwanda Mobile Money Regulations 2018",country:"Rwanda",flag:"🇷🇼",region:"East Africa",group:"EAC",year:2018,status:"in-force",area:"Digital Finance",instrument:"Regulation",act:"Regulation No. 04/2018",enacted:"Nov 2018",inForce:"Nov 2018",authority:"National Bank of Rwanda",closestFW:"GSMA Mobile Money Guidelines",simLevel:"High",oecd:[0.55,0.60,0.62,0.68,0.65],summary:"Comprehensive mobile money regulations governing MTN MoMo and Airtel Money in Rwanda.",tags:["Digital Finance","Mobile Money","East Africa","Rwanda"],whoAffects:"Mobile network operators, PSPs, agents.",sectorImpact:"Telecoms, finance",demand:"Regulate mobile money and ensure consumer protection.",keyObs:"Interoperability, KYC tiers, float management, consumer protection",areas:["Digital Finance"],updated:"Nov 2018"},
  {id:19,title:"Ethiopia Financial Technology Directive 2020",country:"Ethiopia",flag:"🇪🇹",region:"East Africa",group:"IGAD",year:2020,status:"in-force",area:"Digital Finance",instrument:"Regulation",act:"Directive No. FIS/01/2020",enacted:"2020",inForce:"2020",authority:"National Bank of Ethiopia",closestFW:"GSMA Mobile Money Guidelines",simLevel:"Medium",oecd:[0.45,0.50,0.52,0.60,0.55],summary:"First fintech-specific directive in Ethiopia enabling mobile money and non-bank payment providers.",tags:["Digital Finance","Fintech","East Africa","Ethiopia"],whoAffects:"Fintech companies, payment service providers, MFIs.",sectorImpact:"Finance, telecoms",demand:"Enable fintech innovation in Ethiopia.",keyObs:"Non-bank PSP licensing, interoperability, consumer protection",areas:["Digital Finance"],updated:"2020"},
  {id:20,title:"ECOWAS Supplementary Act on Data Protection 2010",country:"ECOWAS",flag:"🌍",region:"West Africa",group:"ECOWAS",year:2010,status:"in-force",area:"Data Protection",instrument:"Supranational Act",act:"A/SA.1/01/10",enacted:"Feb 16, 2010",inForce:"Feb 16, 2010",authority:"ECOWAS Authority",closestFW:"EU Directive 95/46/EC",simLevel:"Medium",oecd:[0.65,0.60,0.62,0.55,0.68],summary:"First supranational data protection framework in Sub-Saharan Africa. Requires member states to enact national laws.",tags:["Data Protection","ECOWAS","Supranational","West Africa"],whoAffects:"All ECOWAS member states and their data controllers.",sectorImpact:"All sectors across 15 countries",demand:"Establish minimum data protection standards across ECOWAS.",keyObs:"Minimum standards, national law requirement, free flow of data",areas:["Data Protection"],updated:"Feb 16, 2010"},
  {id:21,title:"AU Malabo Convention 2014",country:"African Union",flag:"🌍",region:"Continental",group:"AU",year:2014,status:"under-review",area:"Cybersecurity",instrument:"Convention",act:"AU Convention EX.CL/846(XXV)",enacted:"Jun 27, 2014",inForce:"Pending ratification",authority:"African Union",closestFW:"Budapest Convention",simLevel:"Medium",oecd:[0.58,0.54,0.60,0.68,0.62],summary:"Africa's first continental cybersecurity framework covering e-transactions, personal data, and cybercrime.",tags:["Cybersecurity","AU","Continental","Malabo","Under-ratified"],whoAffects:"All African Union member states.",sectorImpact:"All sectors",demand:"Create continental cybersecurity and data protection framework.",keyObs:"E-transactions, data protection, cybercrime, low ratification",areas:["Cybersecurity","Data Protection"],updated:"Jun 27, 2014"},
  {id:22,title:"AU Digital Transformation Strategy 2020-2030",country:"African Union",flag:"🌍",region:"Continental",group:"AU",year:2020,status:"in-force",area:"Digital Economy",instrument:"Strategy",act:"AU DTS 2020-2030",enacted:"2020",inForce:"2020",authority:"African Union Commission",closestFW:"ITU Digital Economy Framework",simLevel:"Medium",oecd:[0.55,0.58,0.52,0.60,0.55],summary:"Overarching strategy for Africa's digital transformation building on ADTP and Agenda 2063.",tags:["Digital Economy","AU","Continental","Strategy"],whoAffects:"All 55 AU member states.",sectorImpact:"All sectors",demand:"Drive digital transformation across Africa.",keyObs:"Smart Africa, ADTP integration, cross-border data, digital IDs",areas:["Digital Economy"],updated:"2020"},
  {id:23,title:"Egypt Personal Data Protection Law 2020",country:"Egypt",flag:"🇪🇬",region:"North Africa",group:"AU",year:2020,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law No. 151 of 2020",enacted:"Jul 13, 2020",inForce:"Oct 2021",authority:"Parliament / PDPL Authority",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.78,0.72,0.75,0.68,0.80],summary:"Egypt's first comprehensive data protection law with data localisation requirements.",tags:["Data Protection","North Africa","Egypt","GDPR-Aligned"],whoAffects:"All data controllers operating in Egypt.",sectorImpact:"All sectors",demand:"Regulate personal data protection in Egypt.",keyObs:"Consent, localisation, sectoral sensitive data, DPC establishment",areas:["Data Protection"],updated:"Oct 2021"},
  {id:24,title:"Morocco Data Protection Law 2009",country:"Morocco",flag:"🇲🇦",region:"North Africa",group:"AU",year:2009,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law 09-08",enacted:"Feb 18, 2009",inForce:"Feb 18, 2009",authority:"Parliament / CNDP",closestFW:"EU Directive 95/46/EC",simLevel:"Medium",oecd:[0.70,0.65,0.68,0.60,0.72],summary:"Morocco's personal data protection law establishing CNDP.",tags:["Data Protection","North Africa","Morocco"],whoAffects:"All data controllers in Morocco.",sectorImpact:"All sectors",demand:"Protect personal data and privacy.",keyObs:"Prior declaration, CNDP authorisation, cross-border transfers",areas:["Data Protection"],updated:"Feb 18, 2009"},
  {id:25,title:"Tanzania Electronic and Postal Communications Act 2010",country:"Tanzania",flag:"🇹🇿",region:"East Africa",group:"EAC",year:2010,status:"in-force",area:"Digital Infrastructure",instrument:"Legislation",act:"EPOCA 2010",enacted:"2010",inForce:"2010",authority:"TCRA",closestFW:"ITU Regulatory Framework",simLevel:"Low",oecd:[0.35,0.40,0.45,0.55,0.42],summary:"Tanzania's primary telecoms legislation establishing TCRA.",tags:["Digital Infrastructure","Telecoms","East Africa","Tanzania"],whoAffects:"Telecoms operators, ISPs, postal operators.",sectorImpact:"Telecoms, ICT",demand:"Regulate electronic communications sector.",keyObs:"TCRA, licensing, spectrum, USF",areas:["Digital Infrastructure","Telecommunications"],updated:"2010"},
  {id:26,title:"Uganda Data Protection and Privacy Act 2019",country:"Uganda",flag:"🇺🇬",region:"East Africa",group:"EAC",year:2019,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"No. 9 of 2019",enacted:"Feb 14, 2019",inForce:"Feb 14, 2019",authority:"Parliament / PDPO",closestFW:"GDPR (EU)",simLevel:"Medium",oecd:[0.72,0.68,0.70,0.62,0.75],summary:"Uganda's data protection law establishing PDPO with data controller registration.",tags:["Data Protection","East Africa","Uganda"],whoAffects:"All data controllers in Uganda.",sectorImpact:"All sectors",demand:"Protect personal data of Ugandans.",keyObs:"PDPO, registration, data subject rights, cross-border",areas:["Data Protection"],updated:"Feb 14, 2019"},
  {id:27,title:"Senegal Personal Data Protection Law 2008",country:"Senegal",flag:"🇸🇳",region:"West Africa",group:"ECOWAS",year:2008,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law No. 2008-12",enacted:"Jan 25, 2008",inForce:"2008",authority:"National Assembly / CDP",closestFW:"EU Directive 95/46/EC",simLevel:"Medium",oecd:[0.65,0.60,0.62,0.55,0.68],summary:"Senegal's data protection law. Among the first in West Africa establishing CDP.",tags:["Data Protection","West Africa","Senegal","Pioneer"],whoAffects:"Data controllers in Senegal.",sectorImpact:"Telecoms, finance",demand:"Protect personal data in Senegal.",keyObs:"CDP authority, registration, transborder flows",areas:["Data Protection"],updated:"2008"},
  {id:28,title:"Botswana Data Protection Act 2018",country:"Botswana",flag:"🇧🇼",region:"Southern Africa",group:"SADC",year:2018,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Act No. 32 of 2018",enacted:"Aug 3, 2018",inForce:"2019",authority:"Parliament / Information Commissioner",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.76,0.72,0.74,0.67,0.79],summary:"Botswana's comprehensive data protection legislation aligning with GDPR principles.",tags:["Data Protection","Southern Africa","Botswana","GDPR-Aligned"],whoAffects:"All data controllers in Botswana.",sectorImpact:"Finance, health, telecoms",demand:"Regulate personal data processing.",keyObs:"Information Commissioner, data subject rights, cross-border transfers",areas:["Data Protection"],updated:"2019"},
  {id:29,title:"Tunisia Digital Economy Law 2000",country:"Tunisia",flag:"🇹🇳",region:"North Africa",group:"AU",year:2000,status:"in-force",area:"Digital Economy",instrument:"Legislation",act:"Law No. 2000-83",enacted:"Aug 9, 2000",inForce:"Aug 9, 2000",authority:"National Assembly",closestFW:"UNCITRAL e-commerce",simLevel:"Low",oecd:[0.38,0.42,0.40,0.50,0.45],summary:"Tunisia's early digital economy law covering e-commerce, e-signatures. Pioneer in North Africa.",tags:["Digital Economy","North Africa","Tunisia","Pioneer"],whoAffects:"E-commerce businesses and digital service providers.",sectorImpact:"Commerce, ICT",demand:"Enable legal framework for digital commerce.",keyObs:"E-signatures, electronic contracts, consumer protection",areas:["Digital Economy"],updated:"2000"},
  {id:30,title:"Ethiopia Computer Crime Proclamation 2016",country:"Ethiopia",flag:"🇪🇹",region:"East Africa",group:"IGAD",year:2016,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"Proclamation No. 958/2016",enacted:"2016",inForce:"2016",authority:"Federal Parliament",closestFW:"Budapest Convention",simLevel:"Low",oecd:[0.40,0.35,0.45,0.60,0.50],summary:"Ethiopia's cybercrime legislation criminalising computer intrusion and data interference.",tags:["Cybersecurity","East Africa","Ethiopia","Controversial"],whoAffects:"All internet users and digital service providers.",sectorImpact:"ICT, media, finance",demand:"Combat cybercrime in Ethiopia.",keyObs:"Broad definitions, press freedom concerns, evidence standards",areas:["Cybersecurity"],updated:"2016"},
  {id:31,title:"Angola Data Protection Law 2022",country:"Angola",flag:"🇦🇴",region:"Southern Africa",group:"SADC",year:2022,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law No. 22/11",enacted:"2022",inForce:"2022",authority:"National Assembly / ANPD",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.75,0.70,0.73,0.67,0.77],summary:"Angola's modern GDPR-aligned data protection law establishing ANPD.",tags:["Data Protection","Southern Africa","Angola","GDPR-Aligned"],whoAffects:"All data controllers in Angola.",sectorImpact:"All sectors",demand:"Protect personal data and privacy in Angola.",keyObs:"ANPD, consent, data subject rights, breach notification",areas:["Data Protection"],updated:"2022"},
  {id:32,title:"Côte d'Ivoire Data Protection Law 2013",country:"Côte d'Ivoire",flag:"🇨🇮",region:"West Africa",group:"ECOWAS",year:2013,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Ordinance No. 2013-450",enacted:"Jun 19, 2013",inForce:"2013",authority:"National Assembly / ARTCI",closestFW:"EU Directive 95/46/EC",simLevel:"Medium",oecd:[0.62,0.58,0.60,0.53,0.65],summary:"Côte d'Ivoire's personal data protection law aligned with ECOWAS Supplementary Act.",tags:["Data Protection","West Africa","Côte d'Ivoire"],whoAffects:"Data controllers in Côte d'Ivoire.",sectorImpact:"Telecoms, finance",demand:"Protect personal data in Côte d'Ivoire.",keyObs:"ARTCI, ECOWAS compliance, registration",areas:["Data Protection"],updated:"2013"},
  {id:33,title:"Zambia Electronic Communications and Transactions Act 2021",country:"Zambia",flag:"🇿🇲",region:"Southern Africa",group:"SADC",year:2021,status:"in-force",area:"Digital Economy",instrument:"Legislation",act:"ECT Act 2021",enacted:"2021",inForce:"2021",authority:"ZICTA",closestFW:"SADC Model Law",simLevel:"Low",oecd:[0.42,0.45,0.48,0.55,0.50],summary:"Zambia's law on electronic communications and digital transactions covering e-commerce.",tags:["Digital Economy","Southern Africa","Zambia"],whoAffects:"E-commerce businesses and digital service providers.",sectorImpact:"Commerce, ICT",demand:"Enable and regulate digital transactions.",keyObs:"ZICTA oversight, e-signatures, consumer protection, data handling",areas:["Digital Economy"],updated:"2021"},
  {id:34,title:"Kenya National ICT Master Plan 2014",country:"Kenya",flag:"🇰🇪",region:"East Africa",group:"EAC",year:2014,status:"in-force",area:"Digital Infrastructure",instrument:"Strategy",act:"ICT Master Plan 2014-2017",enacted:"2014",inForce:"2014",authority:"ICT Ministry",closestFW:"ITU National Broadband Plan",simLevel:"Low",oecd:[0.40,0.45,0.42,0.52,0.48],summary:"Kenya's master plan for ICT infrastructure development targeting broadband connectivity.",tags:["Digital Infrastructure","Kenya","East Africa","Broadband"],whoAffects:"Telecoms sector and government agencies.",sectorImpact:"ICT, government",demand:"Build national digital infrastructure.",keyObs:"NOFBI backbone, broadband target, e-government, last-mile",areas:["Digital Infrastructure"],updated:"2014"},
  {id:35,title:"Nigeria National Broadband Plan 2020-2025",country:"Nigeria",flag:"🇳🇬",region:"West Africa",group:"ECOWAS",year:2020,status:"in-force",area:"Digital Infrastructure",instrument:"Strategy",act:"NNBP 2020-2025",enacted:"2020",inForce:"2020",authority:"Ministry of Communications / NCC",closestFW:"ITU National Broadband Plan",simLevel:"Low",oecd:[0.38,0.42,0.40,0.55,0.45],summary:"Nigeria's 5-year broadband expansion plan targeting 70% penetration by 2025.",tags:["Digital Infrastructure","Nigeria","Broadband","5G"],whoAffects:"Telecoms operators and ISPs.",sectorImpact:"ICT, telecoms",demand:"Expand broadband connectivity across Nigeria.",keyObs:"70% target, spectrum policy, rural access, 5G rollout",areas:["Digital Infrastructure"],updated:"2020"},
  {id:36,title:"South Africa National Integrated ICT Policy 2016",country:"South Africa",flag:"🇿🇦",region:"Southern Africa",group:"SADC",year:2016,status:"in-force",area:"Digital Infrastructure",instrument:"Policy",act:"White Paper on ICT Policy 2016",enacted:"Oct 3, 2016",inForce:"Oct 3, 2016",authority:"DCDT",closestFW:"ITU Regulatory Framework",simLevel:"Medium",oecd:[0.48,0.52,0.50,0.60,0.55],summary:"White paper guiding ICT policy in South Africa covering spectrum, universal service and inclusion.",tags:["Digital Infrastructure","Southern Africa","South Africa"],whoAffects:"Telecoms and broadcasting industries.",sectorImpact:"ICT, broadcast, telecoms",demand:"Transform ICT sector for inclusive digital economy.",keyObs:"Spectrum reform, digital migration, universal service, convergence",areas:["Digital Infrastructure"],updated:"Oct 3, 2016"},
  {id:37,title:"Ghana Electronic Transactions Act 2008",country:"Ghana",flag:"🇬🇭",region:"West Africa",group:"ECOWAS",year:2008,status:"in-force",area:"Digital Economy",instrument:"Legislation",act:"Act 772",enacted:"Dec 27, 2008",inForce:"Dec 27, 2008",authority:"Parliament / NCA",closestFW:"UNCITRAL e-commerce",simLevel:"Low",oecd:[0.40,0.45,0.42,0.52,0.47],summary:"Ghana's electronic transactions law enabling legal recognition of electronic signatures.",tags:["Digital Economy","West Africa","Ghana","E-Commerce"],whoAffects:"E-commerce businesses, government agencies.",sectorImpact:"Commerce, government",demand:"Provide legal framework for electronic transactions.",keyObs:"E-signatures, electronic contracts, NCA role, consumer protection",areas:["Digital Economy"],updated:"Dec 27, 2008"},
  {id:38,title:"AU Continental AI Strategy 2024",country:"African Union",flag:"🌍",region:"Continental",group:"AU",year:2024,status:"under-consultation",area:"Artificial Intelligence",instrument:"Strategy",act:"AU Continental AI Strategy 2024",enacted:"—",inForce:"—",authority:"African Union Commission",closestFW:"OECD AI Principles",simLevel:"High",oecd:[0.82,0.80,0.84,0.78,0.85],summary:"First continental AI strategy for Africa covering AI infrastructure, talent, governance and ethics.",tags:["AI","AU","Continental","Strategy","Under Review"],whoAffects:"All 55 AU member states, AI developers, institutions.",sectorImpact:"All sectors",demand:"Develop responsible AI across Africa.",keyObs:"AI governance, data sovereignty, talent, continental AI hub",areas:["Artificial Intelligence"],updated:"2024"},
  {id:39,title:"Ethiopia National Digital Transformation Strategy 2021",country:"Ethiopia",flag:"🇪🇹",region:"East Africa",group:"IGAD",year:2021,status:"in-force",area:"Digital Economy",instrument:"Strategy",act:"NDTS 2021-2025",enacted:"2021",inForce:"2021",authority:"Ministry of Innovation and Technology",closestFW:"ITU Digital Economy Framework",simLevel:"Low",oecd:[0.42,0.48,0.44,0.55,0.50],summary:"Ethiopia's digital transformation roadmap targeting e-government, digital payments, broadband expansion.",tags:["Digital Economy","East Africa","Ethiopia","Strategy"],whoAffects:"Government agencies, private sector, citizens.",sectorImpact:"Government, finance, education",demand:"Transform Ethiopia's economy through digitisation.",keyObs:"Ethio Telecom reform, mobile money, e-ID, digital skills",areas:["Digital Economy"],updated:"2021"},
  {id:40,title:"Mozambique Data Protection Law 2021",country:"Mozambique",flag:"🇲🇿",region:"Southern Africa",group:"SADC",year:2021,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law No. 7/2021",enacted:"2021",inForce:"2021",authority:"Parliament",closestFW:"GDPR (EU)",simLevel:"Medium",oecd:[0.68,0.62,0.65,0.58,0.70],summary:"Mozambique's data protection legislation establishing supervisory authority.",tags:["Data Protection","Southern Africa","Mozambique"],whoAffects:"Data controllers in Mozambique.",sectorImpact:"All sectors",demand:"Protect personal data in Mozambique.",keyObs:"Supervisory authority, consent, data subject rights",areas:["Data Protection"],updated:"2021"},
  {id:41,title:"Zimbabwe Cybersecurity and Data Protection Act 2021",country:"Zimbabwe",flag:"🇿🇼",region:"Southern Africa",group:"SADC",year:2021,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"Cybersecurity and Data Protection Act 2021",enacted:"Dec 2, 2021",inForce:"Dec 2, 2021",authority:"Parliament / POTRAZ",closestFW:"Budapest Convention",simLevel:"Medium",oecd:[0.58,0.52,0.60,0.70,0.62],summary:"Combined cybersecurity and data protection law with POTRAZ oversight.",tags:["Cybersecurity","Data Protection","Southern Africa","Zimbabwe"],whoAffects:"Internet users, service providers, organisations.",sectorImpact:"All sectors",demand:"Combat cybercrime and protect personal data.",keyObs:"POTRAZ oversight, combined scope, data subject rights",areas:["Cybersecurity","Data Protection"],updated:"Dec 2, 2021"},
  {id:42,title:"Cameroon Electronic Communications Law 2010",country:"Cameroon",flag:"🇨🇲",region:"Central Africa",group:"CEMAC",year:2010,status:"in-force",area:"Digital Infrastructure",instrument:"Legislation",act:"Law No. 2010/012",enacted:"Dec 21, 2010",inForce:"2010",authority:"National Assembly / ART",closestFW:"ITU Regulatory Framework",simLevel:"Low",oecd:[0.35,0.38,0.42,0.50,0.40],summary:"Cameroon's electronic communications law regulating telecoms and internet services.",tags:["Digital Infrastructure","Central Africa","Cameroon"],whoAffects:"Telecoms operators and digital service providers.",sectorImpact:"Telecoms, ICT",demand:"Regulate electronic communications in Cameroon.",keyObs:"ART, licensing, spectrum, interconnection",areas:["Digital Infrastructure"],updated:"2010"},
  {id:43,title:"Namibia Electronic Transactions Act 2019",country:"Namibia",flag:"🇳🇦",region:"Southern Africa",group:"SADC",year:2019,status:"in-force",area:"Digital Economy",instrument:"Legislation",act:"Electronic Transactions Act 4 of 2019",enacted:"Jun 5, 2019",inForce:"2019",authority:"National Assembly",closestFW:"UNCITRAL e-commerce",simLevel:"Low",oecd:[0.40,0.44,0.42,0.52,0.47],summary:"Namibia's law on electronic transactions providing legal recognition of e-signatures.",tags:["Digital Economy","Southern Africa","Namibia"],whoAffects:"Businesses and government engaged in electronic transactions.",sectorImpact:"Commerce, government",demand:"Facilitate e-commerce and digital governance.",keyObs:"E-signatures, legal recognition, consumer protection",areas:["Digital Economy"],updated:"2019"},
  {id:44,title:"Malawi Electronic Transactions and Cybersecurity Act 2016",country:"Malawi",flag:"🇲🇼",region:"Southern Africa",group:"SADC",year:2016,status:"in-force",area:"Cybersecurity",instrument:"Legislation",act:"Electronic Transactions and Cybersecurity Act 2016",enacted:"2016",inForce:"2016",authority:"MACRA",closestFW:"Budapest Convention",simLevel:"Low",oecd:[0.38,0.35,0.45,0.55,0.42],summary:"Combined e-transactions and cybersecurity legislation for Malawi.",tags:["Cybersecurity","Digital Economy","Southern Africa","Malawi"],whoAffects:"Internet users and digital service providers.",sectorImpact:"ICT, government",demand:"Regulate cybersecurity and e-transactions.",keyObs:"MACRA oversight, cybercrime offences, electronic evidence",areas:["Cybersecurity","Digital Economy"],updated:"2016"},
  {id:45,title:"Burkina Faso Personal Data Protection Law 2004",country:"Burkina Faso",flag:"🇧🇫",region:"West Africa",group:"ECOWAS",year:2004,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Law 001/2004",enacted:"Jan 8, 2004",inForce:"2004",authority:"National Assembly / CIL",closestFW:"EU Directive 95/46/EC",simLevel:"Medium",oecd:[0.60,0.55,0.58,0.50,0.62],summary:"One of Africa's earliest data protection laws establishing CIL.",tags:["Data Protection","West Africa","Burkina Faso","Pioneer"],whoAffects:"Data controllers in Burkina Faso.",sectorImpact:"Government, finance",demand:"Protect personal data.",keyObs:"CIL authority, registration, data subject rights",areas:["Data Protection"],updated:"2004"},
  {id:46,title:"African Digital Compact 2023",country:"African Union",flag:"🌍",region:"Continental",group:"AU",year:2023,status:"in-force",area:"Digital Economy",instrument:"Policy Framework",act:"African Digital Compact 2023",enacted:"2023",inForce:"2023",authority:"African Union Commission",closestFW:"UN Global Digital Compact",simLevel:"Medium",oecd:[0.60,0.62,0.58,0.65,0.60],summary:"Framework for Africa's digital governance covering DPI, AI governance, cybersecurity and data flows.",tags:["Digital Economy","AU","Continental","GDC","Digital Governance"],whoAffects:"All AU member states.",sectorImpact:"All sectors",demand:"Position Africa in global digital governance.",keyObs:"DPI, AI ethics, digital rights, cross-border data",areas:["Digital Economy","Artificial Intelligence"],updated:"2023"},
  {id:47,title:"Liberia Data Protection Act 2023",country:"Liberia",flag:"🇱🇷",region:"West Africa",group:"ECOWAS",year:2023,status:"in-force",area:"Data Protection",instrument:"Legislation",act:"Data Protection Act 2023",enacted:"2023",inForce:"2023",authority:"National Legislature",closestFW:"GDPR (EU)",simLevel:"High",oecd:[0.74,0.70,0.72,0.65,0.76],summary:"Liberia's first comprehensive GDPR-aligned data protection law.",tags:["Data Protection","West Africa","Liberia","GDPR-Aligned"],whoAffects:"Data controllers in Liberia.",sectorImpact:"All sectors",demand:"Protect personal data in Liberia.",keyObs:"DPA establishment, consent, data subject rights, GDPR alignment",areas:["Data Protection"],updated:"2023"},
  {id:48,title:"Somalia Cybercrime Law 2023",country:"Somalia",flag:"🇸🇴",region:"East Africa",group:"IGAD",year:2023,status:"under-review",area:"Cybersecurity",instrument:"Legislation",act:"Cybercrime Law 2023",enacted:"2023",inForce:"pending",authority:"Federal Parliament",closestFW:"Budapest Convention",simLevel:"Low",oecd:[0.35,0.30,0.40,0.55,0.38],summary:"Somalia's nascent cybercrime framework with implementation challenges.",tags:["Cybersecurity","East Africa","Somalia","Emerging"],whoAffects:"Internet users and service providers.",sectorImpact:"ICT, telecoms",demand:"Establish basic cybercrime framework.",keyObs:"Basic offences, implementation challenges, capacity building needed",areas:["Cybersecurity"],updated:"2023"},
  {id:49,title:"Benin Digital Economy Law 2017",country:"Benin",flag:"🇧🇯",region:"West Africa",group:"ECOWAS",year:2017,status:"in-force",area:"Digital Economy",instrument:"Legislation",act:"Law No. 2017-20",enacted:"Apr 20, 2017",inForce:"2017",authority:"National Assembly",closestFW:"ECOWAS Digital Framework",simLevel:"Low",oecd:[0.42,0.45,0.43,0.52,0.48],summary:"Benin's digital economy framework covering e-commerce and electronic transactions.",tags:["Digital Economy","West Africa","Benin"],whoAffects:"Digital businesses and consumers.",sectorImpact:"Commerce, government",demand:"Enable digital economy in Benin.",keyObs:"E-commerce, e-signatures, consumer protection, APDP",areas:["Digital Economy"],updated:"2017"},
  {id:50,title:"Tunisia National AI Strategy 2019",country:"Tunisia",flag:"🇹🇳",region:"North Africa",group:"AU",year:2019,status:"in-force",area:"Artificial Intelligence",instrument:"Strategy",act:"National AI Strategy 2019",enacted:"2019",inForce:"2019",authority:"Ministry of ICT",closestFW:"OECD AI Principles",simLevel:"Medium",oecd:[0.68,0.65,0.70,0.62,0.70],summary:"Tunisia's national AI strategy focusing on AI for economic competitiveness and digital government.",tags:["AI","Strategy","North Africa","Tunisia"],whoAffects:"AI sector, government, research institutions.",sectorImpact:"ICT, government, agriculture",demand:"Develop AI ecosystem in Tunisia.",keyObs:"AI talent, smart cities, AI-driven public services, research",areas:["Artificial Intelligence"],updated:"2019"},
]

async function main() {
  console.log('🌍  Africa Digital Policy Tracker — Supabase Seed')
  console.log(`📡  URL: ${url.slice(0, 40)}...`)
  console.log(`🔑  Key: ${key.slice(0, 20)}...`)
  console.log('')

  // 1. Create table if it doesn't exist (via SQL via RPC if available, else just try upsert)
  console.log('📋  Upserting 50 policies...')

  // Map JS fields to DB column names
  const rows = POLICIES.map(({ inForce, closestFW, simLevel, whoAffects, sectorImpact, keyObs, ...rest }) => ({
    ...rest,
    inForce,
    closestFW,
    simLevel,
    whoAffects,
    sectorImpact,
    keyObs,
  }))

  const { error, count } = await supabase
    .from('policies')
    .upsert(rows, { onConflict: 'id', count: 'exact' })

  if (error) {
    console.error('❌  Upsert failed:', error.message)
    console.log('')
    console.log('👉  If the table does not exist yet, run the migration first:')
    console.log('    psql $DATABASE_URL -f supabase/migration.sql')
    console.log('    Then re-run this seed script.')
    process.exit(1)
  }

  console.log(`✅  Upserted ${count ?? POLICIES.length} policies successfully!`)
  console.log('')
  console.log('🚀  Your Supabase database is ready.')
}

main().catch((err) => { console.error(err); process.exit(1) })
